# Nginx reverse proxy configuration
server {

    listen 80;

    # API routes
    location /api/ {
        proxy_pass http://backend:5000;
    }

    # Short URL redirect routes
    location ~ "^/[A-Za-z0-9]{6}$" {
        proxy_pass http://backend:5000;
    }

    # Frontend routes
    location / {
        proxy_pass http://frontend:4173;
    }
}